// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/fuse_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Owner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_proto_fuse_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{0}
}

func (x *Owner) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Owner) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type FileAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=valid,proto3" json:"valid,omitempty"`                            // how long FileAttr can be cached
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`                           // inode number
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                             // size in bytes
	ATime         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=a_time,json=aTime,proto3" json:"a_time,omitempty"`               // time of last access
	MTime         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=m_time,json=mTime,proto3" json:"m_time,omitempty"`               // time of last modification
	CTime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=c_time,json=cTime,proto3" json:"c_time,omitempty"`               // time of last inode change
	Mode          uint32                 `protobuf:"varint,7,opt,name=mode,proto3" json:"mode,omitempty"`                             // file mode
	NLink         uint32                 `protobuf:"varint,8,opt,name=n_link,json=nLink,proto3" json:"n_link,omitempty"`              // number of links
	Owner         *Owner                 `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`                            // owner user ID and group ID
	BlockSize     uint32                 `protobuf:"varint,10,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"` // preferred blocksize for filesystem I/O
	Flags         uint32                 `protobuf:"varint,11,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAttr) Reset() {
	*x = FileAttr{}
	mi := &file_proto_fuse_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttr) ProtoMessage() {}

func (x *FileAttr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttr.ProtoReflect.Descriptor instead.
func (*FileAttr) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{1}
}

func (x *FileAttr) GetValid() *timestamppb.Timestamp {
	if x != nil {
		return x.Valid
	}
	return nil
}

func (x *FileAttr) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *FileAttr) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileAttr) GetATime() *timestamppb.Timestamp {
	if x != nil {
		return x.ATime
	}
	return nil
}

func (x *FileAttr) GetMTime() *timestamppb.Timestamp {
	if x != nil {
		return x.MTime
	}
	return nil
}

func (x *FileAttr) GetCTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CTime
	}
	return nil
}

func (x *FileAttr) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileAttr) GetNLink() uint32 {
	if x != nil {
		return x.NLink
	}
	return 0
}

func (x *FileAttr) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *FileAttr) GetBlockSize() uint32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *FileAttr) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Attr          *FileAttr              `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_fuse_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Node) GetAttr() *FileAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"` // node to perform lookup operation in
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // path of node to look for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_proto_fuse_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{3}
}

func (x *LookupRequest) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *LookupRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`    // path of new directory to be created
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`   // file mode
	Umask         uint32                 `protobuf:"varint,3,opt,name=umask,proto3" json:"umask,omitempty"` // umask of new directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_proto_fuse_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{4}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MkdirRequest) GetUmask() uint32 {
	if x != nil {
		return x.Umask
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Flags         uint32                 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Umask         uint32                 `protobuf:"varint,4,opt,name=umask,proto3" json:"umask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_fuse_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *CreateRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CreateRequest) GetUmask() uint32 {
	if x != nil {
		return x.Umask
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	EntryValid    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=entry_valid,json=entryValid,proto3" json:"entry_valid,omitempty"`
	Attr          *FileAttr              `protobuf:"bytes,4,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_fuse_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateResponse) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *CreateResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *CreateResponse) GetEntryValid() *timestamppb.Timestamp {
	if x != nil {
		return x.EntryValid
	}
	return nil
}

func (x *CreateResponse) GetAttr() *FileAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentNode    *Node                  `protobuf:"bytes,1,opt,name=parent_node,json=parentNode,proto3" json:"parent_node,omitempty"` // file to write to
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`                          // point to start writing within file
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	WriteFlags    uint32                 `protobuf:"varint,4,opt,name=write_flags,json=writeFlags,proto3" json:"write_flags,omitempty"`
	LockOwner     uint64                 `protobuf:"varint,5,opt,name=lock_owner,json=lockOwner,proto3" json:"lock_owner,omitempty"` // identify the owner of a particular lock
	FileFlags     uint32                 `protobuf:"varint,6,opt,name=file_flags,json=fileFlags,proto3" json:"file_flags,omitempty"` // example; os.O_WRONLY
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_fuse_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{7}
}

func (x *WriteRequest) GetParentNode() *Node {
	if x != nil {
		return x.ParentNode
	}
	return nil
}

func (x *WriteRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteRequest) GetWriteFlags() uint32 {
	if x != nil {
		return x.WriteFlags
	}
	return 0
}

func (x *WriteRequest) GetLockOwner() uint64 {
	if x != nil {
		return x.LockOwner
	}
	return 0
}

func (x *WriteRequest) GetFileFlags() uint32 {
	if x != nil {
		return x.FileFlags
	}
	return 0
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_proto_fuse_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{8}
}

func (x *RenameRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *RenameRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type Dirent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"` // inode number
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"` // path of the entry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dirent) Reset() {
	*x = Dirent{}
	mi := &file_proto_fuse_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dirent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dirent) ProtoMessage() {}

func (x *Dirent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dirent.ProtoReflect.Descriptor instead.
func (*Dirent) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{9}
}

func (x *Dirent) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *Dirent) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Dirent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadDirAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Dirent              `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirAllResponse) Reset() {
	*x = ReadDirAllResponse{}
	mi := &file_proto_fuse_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirAllResponse) ProtoMessage() {}

func (x *ReadDirAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirAllResponse.ProtoReflect.Descriptor instead.
func (*ReadDirAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReadDirAllResponse) GetEntries() []*Dirent {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ReadAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllResponse) Reset() {
	*x = ReadAllResponse{}
	mi := &file_proto_fuse_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllResponse) ProtoMessage() {}

func (x *ReadAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllResponse.ProtoReflect.Descriptor instead.
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReadAllResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  uint64                 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_fuse_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{12}
}

func (x *WriteResponse) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type LinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkRequest) Reset() {
	*x = LinkRequest{}
	mi := &file_proto_fuse_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRequest) ProtoMessage() {}

func (x *LinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRequest.ProtoReflect.Descriptor instead.
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{13}
}

func (x *LinkRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *LinkRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type LinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkResponse) Reset() {
	*x = LinkResponse{}
	mi := &file_proto_fuse_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkResponse) ProtoMessage() {}

func (x *LinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkResponse.ProtoReflect.Descriptor instead.
func (*LinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{14}
}

func (x *LinkResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ExpectedHash  string                 `protobuf:"bytes,2,opt,name=expected_hash,json=expectedHash,proto3" json:"expected_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_proto_fuse_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{15}
}

func (x *DownloadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DownloadRequest) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_fuse_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fuse_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_fuse_service_proto_rawDescGZIP(), []int{16}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

var File_proto_fuse_service_proto protoreflect.FileDescriptor

const file_proto_fuse_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/fuse_service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n" +
	"\x05Owner\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x02 \x01(\rR\x03gid\"\xfd\x02\n" +
	"\bFileAttr\x120\n" +
	"\x05valid\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05valid\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x121\n" +
	"\x06a_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05aTime\x121\n" +
	"\x06m_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05mTime\x121\n" +
	"\x06c_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05cTime\x12\x12\n" +
	"\x04mode\x18\a \x01(\rR\x04mode\x12\x15\n" +
	"\x06n_link\x18\b \x01(\rR\x05nLink\x12\x1c\n" +
	"\x05owner\x18\t \x01(\v2\x06.OwnerR\x05owner\x12\x1d\n" +
	"\n" +
	"block_size\x18\n" +
	" \x01(\rR\tblockSize\x12\x14\n" +
	"\x05flags\x18\v \x01(\rR\x05flags\"9\n" +
	"\x04Node\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\x04attr\x18\x02 \x01(\v2\t.FileAttrR\x04attr\">\n" +
	"\rLookupRequest\x12\x19\n" +
	"\x04node\x18\x01 \x01(\v2\x05.NodeR\x04node\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"L\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x14\n" +
	"\x05umask\x18\x03 \x01(\rR\x05umask\"c\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05flags\x18\x02 \x01(\rR\x05flags\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x14\n" +
	"\x05umask\x18\x04 \x01(\rR\x05umask\"\xa5\x01\n" +
	"\x0eCreateResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12;\n" +
	"\ventry_valid\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"entryValid\x12\x1d\n" +
	"\x04attr\x18\x04 \x01(\v2\t.FileAttrR\x04attr\"\xc1\x01\n" +
	"\fWriteRequest\x12&\n" +
	"\vparent_node\x18\x01 \x01(\v2\x05.NodeR\n" +
	"parentNode\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1f\n" +
	"\vwrite_flags\x18\x04 \x01(\rR\n" +
	"writeFlags\x12\x1d\n" +
	"\n" +
	"lock_owner\x18\x05 \x01(\x04R\tlockOwner\x12\x1d\n" +
	"\n" +
	"file_flags\x18\x06 \x01(\rR\tfileFlags\"E\n" +
	"\rRenameRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\"F\n" +
	"\x06Dirent\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"7\n" +
	"\x12ReadDirAllResponse\x12!\n" +
	"\aentries\x18\x01 \x03(\v2\a.DirentR\aentries\"%\n" +
	"\x0fReadAllResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"4\n" +
	"\rWriteResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x04R\fbytesWritten\"C\n" +
	"\vLinkRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\")\n" +
	"\fLinkResponse\x12\x19\n" +
	"\x04node\x18\x01 \x01(\v2\x05.NodeR\x04node\"J\n" +
	"\x0fDownloadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rexpected_hash\x18\x02 \x01(\tR\fexpectedHash\"V\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize2\xfa\x03\n" +
	"\vFuseService\x12!\n" +
	"\x06Lookup\x12\x0e.LookupRequest\x1a\x05.Node\"\x00\x12*\n" +
	"\n" +
	"ReadDirAll\x12\x05.Node\x1a\x13.ReadDirAllResponse\"\x00\x12\x1f\n" +
	"\x05Mkdir\x12\r.MkdirRequest\x1a\x05.Node\"\x00\x12(\n" +
	"\x05Rmdir\x12\x05.Node\x1a\x16.google.protobuf.Empty\"\x00\x12\x1d\n" +
	"\aGetattr\x12\x05.Node\x1a\t.FileAttr\"\x00\x12+\n" +
	"\x06Create\x12\x0e.CreateRequest\x1a\x0f.CreateResponse\"\x00\x12(\n" +
	"\aSymlink\x12\f.LinkRequest\x1a\r.LinkResponse\"\x00\x12%\n" +
	"\x04Link\x12\f.LinkRequest\x1a\r.LinkResponse\"\x00\x12$\n" +
	"\aReadAll\x12\x05.Node\x1a\x10.ReadAllResponse\"\x00\x12(\n" +
	"\x05Write\x12\r.WriteRequest\x1a\x0e.WriteResponse\"\x00\x122\n" +
	"\x06Rename\x12\x0e.RenameRequest\x1a\x16.google.protobuf.Empty\"\x00\x120\n" +
	"\fDownloadFile\x12\x10.DownloadRequest\x1a\n" +
	".FileChunk\"\x000\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_fuse_service_proto_rawDescOnce sync.Once
	file_proto_fuse_service_proto_rawDescData []byte
)

func file_proto_fuse_service_proto_rawDescGZIP() []byte {
	file_proto_fuse_service_proto_rawDescOnce.Do(func() {
		file_proto_fuse_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fuse_service_proto_rawDesc), len(file_proto_fuse_service_proto_rawDesc)))
	})
	return file_proto_fuse_service_proto_rawDescData
}

var file_proto_fuse_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_fuse_service_proto_goTypes = []any{
	(*Owner)(nil),                 // 0: Owner
	(*FileAttr)(nil),              // 1: FileAttr
	(*Node)(nil),                  // 2: Node
	(*LookupRequest)(nil),         // 3: LookupRequest
	(*MkdirRequest)(nil),          // 4: MkdirRequest
	(*CreateRequest)(nil),         // 5: CreateRequest
	(*CreateResponse)(nil),        // 6: CreateResponse
	(*WriteRequest)(nil),          // 7: WriteRequest
	(*RenameRequest)(nil),         // 8: RenameRequest
	(*Dirent)(nil),                // 9: Dirent
	(*ReadDirAllResponse)(nil),    // 10: ReadDirAllResponse
	(*ReadAllResponse)(nil),       // 11: ReadAllResponse
	(*WriteResponse)(nil),         // 12: WriteResponse
	(*LinkRequest)(nil),           // 13: LinkRequest
	(*LinkResponse)(nil),          // 14: LinkResponse
	(*DownloadRequest)(nil),       // 15: DownloadRequest
	(*FileChunk)(nil),             // 16: FileChunk
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 18: google.protobuf.Empty
}
var file_proto_fuse_service_proto_depIdxs = []int32{
	17, // 0: FileAttr.valid:type_name -> google.protobuf.Timestamp
	17, // 1: FileAttr.a_time:type_name -> google.protobuf.Timestamp
	17, // 2: FileAttr.m_time:type_name -> google.protobuf.Timestamp
	17, // 3: FileAttr.c_time:type_name -> google.protobuf.Timestamp
	0,  // 4: FileAttr.owner:type_name -> Owner
	1,  // 5: Node.attr:type_name -> FileAttr
	2,  // 6: LookupRequest.node:type_name -> Node
	17, // 7: CreateResponse.entry_valid:type_name -> google.protobuf.Timestamp
	1,  // 8: CreateResponse.attr:type_name -> FileAttr
	2,  // 9: WriteRequest.parent_node:type_name -> Node
	9,  // 10: ReadDirAllResponse.entries:type_name -> Dirent
	2,  // 11: LinkResponse.node:type_name -> Node
	3,  // 12: FuseService.Lookup:input_type -> LookupRequest
	2,  // 13: FuseService.ReadDirAll:input_type -> Node
	4,  // 14: FuseService.Mkdir:input_type -> MkdirRequest
	2,  // 15: FuseService.Rmdir:input_type -> Node
	2,  // 16: FuseService.Getattr:input_type -> Node
	5,  // 17: FuseService.Create:input_type -> CreateRequest
	13, // 18: FuseService.Symlink:input_type -> LinkRequest
	13, // 19: FuseService.Link:input_type -> LinkRequest
	2,  // 20: FuseService.ReadAll:input_type -> Node
	7,  // 21: FuseService.Write:input_type -> WriteRequest
	8,  // 22: FuseService.Rename:input_type -> RenameRequest
	15, // 23: FuseService.DownloadFile:input_type -> DownloadRequest
	2,  // 24: FuseService.Lookup:output_type -> Node
	10, // 25: FuseService.ReadDirAll:output_type -> ReadDirAllResponse
	2,  // 26: FuseService.Mkdir:output_type -> Node
	18, // 27: FuseService.Rmdir:output_type -> google.protobuf.Empty
	1,  // 28: FuseService.Getattr:output_type -> FileAttr
	6,  // 29: FuseService.Create:output_type -> CreateResponse
	14, // 30: FuseService.Symlink:output_type -> LinkResponse
	14, // 31: FuseService.Link:output_type -> LinkResponse
	11, // 32: FuseService.ReadAll:output_type -> ReadAllResponse
	12, // 33: FuseService.Write:output_type -> WriteResponse
	18, // 34: FuseService.Rename:output_type -> google.protobuf.Empty
	16, // 35: FuseService.DownloadFile:output_type -> FileChunk
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_fuse_service_proto_init() }
func file_proto_fuse_service_proto_init() {
	if File_proto_fuse_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fuse_service_proto_rawDesc), len(file_proto_fuse_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fuse_service_proto_goTypes,
		DependencyIndexes: file_proto_fuse_service_proto_depIdxs,
		MessageInfos:      file_proto_fuse_service_proto_msgTypes,
	}.Build()
	File_proto_fuse_service_proto = out.File
	file_proto_fuse_service_proto_goTypes = nil
	file_proto_fuse_service_proto_depIdxs = nil
}
